"""initial_schema

Revision ID: de7d957eccec
Revises: 
Create Date: 2026-07-31 13:06:17.417145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de7d957eccec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', name='adminrole', native_enum=False, length=16), server_default='admin', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admins'))
    )
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.create_table('quizzes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Draft', 'Ready', 'InUse', 'Archived', 'Deleted', name='quizstatus', native_enum=False, length=16), server_default='Draft', nullable=False),
    sa.Column('branding_media_file_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quizzes'))
    )
    op.create_index(op.f('ix_quizzes_status'), 'quizzes', ['status'], unique=False)
    op.create_index('ix_quizzes_status_title', 'quizzes', ['status', 'title'], unique=False)
    op.create_index(op.f('ix_quizzes_title'), 'quizzes', ['title'], unique=False)
    op.create_table('security_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('login_success', 'logout', 'login_failed', name='securityeventtype', native_enum=False, length=32), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_logs'))
    )
    op.create_index(op.f('ix_security_logs_event_type'), 'security_logs', ['event_type'], unique=False)
    op.create_table('live_rooms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quiz_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Enum('Setup', 'Lobby', 'Active', 'Paused', 'SectionBreak', 'Completed', 'Closed', name='roomstate', native_enum=False, length=16), server_default='Setup', nullable=False),
    sa.Column('lobby_sub_state', sa.Enum('LobbyOpen', 'LobbyClosed', name='lobbysubstate', native_enum=False, length=16), nullable=True),
    sa.Column('room_code', sa.String(length=6), nullable=False),
    sa.Column('secret_token', sa.String(length=64), nullable=False),
    sa.Column('quiz_title_snapshot', sa.String(length=255), nullable=False),
    sa.Column('current_question_index', sa.Integer(), nullable=True),
    sa.Column('codes_expired', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_live_rooms_quiz_id_quizzes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_live_rooms'))
    )
    op.create_index(op.f('ix_live_rooms_completed_at'), 'live_rooms', ['completed_at'], unique=False)
    op.create_index(op.f('ix_live_rooms_quiz_id'), 'live_rooms', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_live_rooms_room_code'), 'live_rooms', ['room_code'], unique=True)
    op.create_index(op.f('ix_live_rooms_secret_token'), 'live_rooms', ['secret_token'], unique=True)
    op.create_index(op.f('ix_live_rooms_state'), 'live_rooms', ['state'], unique=False)
    op.create_table('media_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('category', sa.Enum('question_image', 'question_audio', 'quiz_branding', 'platform_branding', name='mediacategory', native_enum=False, length=32), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('quiz_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_media_files_quiz_id_quizzes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_files'))
    )
    op.create_index(op.f('ix_media_files_category'), 'media_files', ['category'], unique=False)
    op.create_index(op.f('ix_media_files_quiz_id'), 'media_files', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_media_files_storage_key'), 'media_files', ['storage_key'], unique=True)
    # Deferred FK: quizzes.branding_media_file_id → media_files (circular with media_files.quiz_id).
    # batch_alter_table is required for SQLite; also works on PostgreSQL.
    with op.batch_alter_table('quizzes') as batch_op:
        batch_op.create_foreign_key(
            'fk_quizzes_branding_media_file_id_media_files',
            'media_files',
            ['branding_media_file_id'],
            ['id'],
            ondelete='SET NULL',
        )
    op.create_table('quiz_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quiz_id', sa.Uuid(), nullable=False),
    sa.Column('question_advance_mode', sa.Enum('manual', 'automatic', name='questionadvancemode', native_enum=False, length=16), server_default='manual', nullable=False),
    sa.Column('answer_reveal_behavior', sa.Enum('after_each', 'session_end', name='answerrevealbehavior', native_enum=False, length=16), server_default='after_each', nullable=False),
    sa.Column('time_bonus_enabled', sa.Boolean(), nullable=False),
    sa.Column('time_bonus_max_points', sa.Integer(), nullable=False),
    sa.Column('streak_bonus_enabled', sa.Boolean(), nullable=False),
    sa.Column('streak_bonus_rules', sa.JSON(), nullable=True),
    sa.Column('question_order_shuffle', sa.Boolean(), nullable=False),
    sa.Column('answer_option_shuffle', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_quiz_configs_quiz_id_quizzes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_configs')),
    sa.UniqueConstraint('quiz_id', name=op.f('uq_quiz_configs_quiz_id'))
    )
    op.create_table('sections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quiz_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_sections_quiz_id_quizzes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sections')),
    sa.UniqueConstraint('quiz_id', 'sort_order', name='uq_sections_quiz_id_sort_order')
    )
    op.create_index(op.f('ix_sections_quiz_id'), 'sections', ['quiz_id'], unique=False)
    op.create_table('participants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('live_room_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('session_token', sa.String(length=64), nullable=False),
    sa.Column('state', sa.Enum('Joining', 'InLobby', 'Active', 'Answering', 'Buzzing', 'BuzzUnlocked', 'Answered', 'Waiting', 'Disconnected', 'Reconnecting', 'Kicked', 'Banned', 'SessionEnded', name='participantstate', native_enum=False, length=16), server_default='Joining', nullable=False),
    sa.Column('connection_status', sa.Enum('connected', 'disconnected', name='connectionstatus', native_enum=False, length=16), server_default='connected', nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['live_room_id'], ['live_rooms.id'], name=op.f('fk_participants_live_room_id_live_rooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participants')),
    sa.UniqueConstraint('live_room_id', 'display_name', name='uq_participants_live_room_id_display_name'),
    sa.UniqueConstraint('live_room_id', 'email', name='uq_participants_live_room_id_email')
    )
    op.create_index(op.f('ix_participants_live_room_id'), 'participants', ['live_room_id'], unique=False)
    op.create_index(op.f('ix_participants_session_token'), 'participants', ['session_token'], unique=True)
    op.create_table('platform_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('platform_name', sa.String(length=128), nullable=False),
    sa.Column('logo_media_file_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['logo_media_file_id'], ['media_files.id'], name=op.f('fk_platform_settings_logo_media_file_id_media_files'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_settings'))
    )
    op.create_table('questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('question_type', sa.Enum('Text', 'Image', 'Audio', 'Buzzer', name='questiontype', native_enum=False, length=16), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('media_file_id', sa.Uuid(), nullable=True),
    sa.Column('base_points', sa.Integer(), nullable=False),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('allow_multiple_correct', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], name=op.f('fk_questions_media_file_id_media_files'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('fk_questions_section_id_sections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions')),
    sa.UniqueConstraint('section_id', 'sort_order', name='uq_questions_section_id_sort_order')
    )
    op.create_index(op.f('ix_questions_section_id'), 'questions', ['section_id'], unique=False)
    op.create_table('room_bans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('live_room_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['live_room_id'], ['live_rooms.id'], name=op.f('fk_room_bans_live_room_id_live_rooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_bans')),
    sa.UniqueConstraint('live_room_id', 'email', name='uq_room_bans_live_room_id_email')
    )
    op.create_index(op.f('ix_room_bans_live_room_id'), 'room_bans', ['live_room_id'], unique=False)
    op.create_table('room_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('live_room_id', sa.Uuid(), nullable=False),
    sa.Column('question_advance_mode', sa.Enum('manual', 'automatic', name='questionadvancemode', native_enum=False, length=16), nullable=False),
    sa.Column('answer_reveal_behavior', sa.Enum('after_each', 'session_end', name='answerrevealbehavior', native_enum=False, length=16), nullable=False),
    sa.Column('time_bonus_enabled', sa.Boolean(), nullable=False),
    sa.Column('time_bonus_max_points', sa.Integer(), nullable=False),
    sa.Column('streak_bonus_enabled', sa.Boolean(), nullable=False),
    sa.Column('streak_bonus_rules', sa.JSON(), nullable=True),
    sa.Column('question_order_shuffle', sa.Boolean(), nullable=False),
    sa.Column('answer_option_shuffle', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['live_room_id'], ['live_rooms.id'], name=op.f('fk_room_configs_live_room_id_live_rooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_configs')),
    sa.UniqueConstraint('live_room_id', name=op.f('uq_room_configs_live_room_id'))
    )
    op.create_table('session_sections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('live_room_id', sa.Uuid(), nullable=False),
    sa.Column('source_section_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['live_room_id'], ['live_rooms.id'], name=op.f('fk_session_sections_live_room_id_live_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_section_id'], ['sections.id'], name=op.f('fk_session_sections_source_section_id_sections'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_sections')),
    sa.UniqueConstraint('live_room_id', 'sort_order', name='uq_session_sections_live_room_id_sort_order')
    )
    op.create_index(op.f('ix_session_sections_live_room_id'), 'session_sections', ['live_room_id'], unique=False)
    op.create_table('answer_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_answer_options_question_id_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answer_options')),
    sa.UniqueConstraint('question_id', 'sort_order', name='uq_answer_options_question_id_sort_order')
    )
    op.create_index(op.f('ix_answer_options_question_id'), 'answer_options', ['question_id'], unique=False)
    op.create_table('session_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('live_room_id', sa.Uuid(), nullable=False),
    sa.Column('session_section_id', sa.Uuid(), nullable=False),
    sa.Column('source_question_id', sa.Uuid(), nullable=True),
    sa.Column('question_type', sa.Enum('Text', 'Image', 'Audio', 'Buzzer', name='questiontype', native_enum=False, length=16), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('media_file_id', sa.Uuid(), nullable=True),
    sa.Column('base_points', sa.Integer(), nullable=False),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('allow_multiple_correct', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('Pending', 'Open', 'BuzzerOpen', 'BuzzerLocked', 'Closed', 'Revealed', 'Scored', name='sessionquestionstate', native_enum=False, length=16), server_default='Pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['live_room_id'], ['live_rooms.id'], name=op.f('fk_session_questions_live_room_id_live_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], name=op.f('fk_session_questions_media_file_id_media_files'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_section_id'], ['session_sections.id'], name=op.f('fk_session_questions_session_section_id_session_sections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_question_id'], ['questions.id'], name=op.f('fk_session_questions_source_question_id_questions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_questions')),
    sa.UniqueConstraint('live_room_id', 'sort_order', name='uq_session_questions_live_room_id_sort_order')
    )
    op.create_index(op.f('ix_session_questions_live_room_id'), 'session_questions', ['live_room_id'], unique=False)
    op.create_index(op.f('ix_session_questions_session_section_id'), 'session_questions', ['session_section_id'], unique=False)
    op.create_table('responses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('session_question_id', sa.Uuid(), nullable=False),
    sa.Column('selected_option_ids', sa.JSON(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('is_unanswered', sa.Boolean(), nullable=False),
    sa.Column('base_points_earned', sa.Integer(), nullable=False),
    sa.Column('time_bonus_earned', sa.Integer(), nullable=False),
    sa.Column('streak_bonus_earned', sa.Integer(), nullable=False),
    sa.Column('total_points_earned', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], name=op.f('fk_responses_participant_id_participants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_question_id'], ['session_questions.id'], name=op.f('fk_responses_session_question_id_session_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_responses')),
    sa.UniqueConstraint('participant_id', 'session_question_id', name='uq_responses_participant_id_session_question_id')
    )
    op.create_index(op.f('ix_responses_participant_id'), 'responses', ['participant_id'], unique=False)
    op.create_index('ix_responses_participant_id_session_question_id', 'responses', ['participant_id', 'session_question_id'], unique=False)
    op.create_index(op.f('ix_responses_session_question_id'), 'responses', ['session_question_id'], unique=False)
    op.create_table('session_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_question_id', sa.Uuid(), nullable=False),
    sa.Column('source_option_id', sa.Uuid(), nullable=True),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_question_id'], ['session_questions.id'], name=op.f('fk_session_options_session_question_id_session_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_option_id'], ['answer_options.id'], name=op.f('fk_session_options_source_option_id_answer_options'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_options')),
    sa.UniqueConstraint('session_question_id', 'sort_order', name='uq_session_options_session_question_id_sort_order')
    )
    op.create_index(op.f('ix_session_options_session_question_id'), 'session_options', ['session_question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_options_session_question_id'), table_name='session_options')
    op.drop_table('session_options')
    op.drop_index(op.f('ix_responses_session_question_id'), table_name='responses')
    op.drop_index('ix_responses_participant_id_session_question_id', table_name='responses')
    op.drop_index(op.f('ix_responses_participant_id'), table_name='responses')
    op.drop_table('responses')
    op.drop_index(op.f('ix_session_questions_session_section_id'), table_name='session_questions')
    op.drop_index(op.f('ix_session_questions_live_room_id'), table_name='session_questions')
    op.drop_table('session_questions')
    op.drop_index(op.f('ix_answer_options_question_id'), table_name='answer_options')
    op.drop_table('answer_options')
    op.drop_index(op.f('ix_session_sections_live_room_id'), table_name='session_sections')
    op.drop_table('session_sections')
    op.drop_table('room_configs')
    op.drop_index(op.f('ix_room_bans_live_room_id'), table_name='room_bans')
    op.drop_table('room_bans')
    op.drop_index(op.f('ix_questions_section_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_table('platform_settings')
    op.drop_index(op.f('ix_participants_session_token'), table_name='participants')
    op.drop_index(op.f('ix_participants_live_room_id'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_sections_quiz_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_table('quiz_configs')
    op.drop_index(op.f('ix_media_files_storage_key'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_quiz_id'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_category'), table_name='media_files')
    with op.batch_alter_table('quizzes') as batch_op:
        batch_op.drop_constraint('fk_quizzes_branding_media_file_id_media_files', type_='foreignkey')
    op.drop_table('media_files')
    op.drop_index(op.f('ix_live_rooms_state'), table_name='live_rooms')
    op.drop_index(op.f('ix_live_rooms_secret_token'), table_name='live_rooms')
    op.drop_index(op.f('ix_live_rooms_room_code'), table_name='live_rooms')
    op.drop_index(op.f('ix_live_rooms_quiz_id'), table_name='live_rooms')
    op.drop_index(op.f('ix_live_rooms_completed_at'), table_name='live_rooms')
    op.drop_table('live_rooms')
    op.drop_index(op.f('ix_security_logs_event_type'), table_name='security_logs')
    op.drop_table('security_logs')
    op.drop_index(op.f('ix_quizzes_title'), table_name='quizzes')
    op.drop_index('ix_quizzes_status_title', table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_status'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
